name: Container
on: push
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: golang:1.21
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # go should already be setup due to the container
      - name: Test
        run: go test -v ./...