# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  # Triggers the workflow on push or
  # Pull request events but only for the "main" branch
  push:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Test
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with: # with keyword is used to pass inputs to actions
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

  deploy:
    needs: [build, test] # this job will run after the build job is completed
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: echo "Deploying... (mimicking a deployment)"