# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  # Triggers the workflow on push or
  # Pull request events but only for the "main" branch
  push:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  version-check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.publish-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Publish the version from Readme
        id: publish-version
        run: grep 'Version:' README.md | cut -d ' ' -f 2 | xargs -I{} echo "version={}" >> $GITHUB_OUTPUT
        # grep 'Version:' README.md searches for lines containing "Version:" in
        # the README.md file.
        # cut -d ' ' -f 2 splits the matched line by spaces (-d ' ') and selects
        # the second field (-f 2), which is the SemVer version.
        # xargs -I{} is used to pass the extracted version as a placeholder {}
        # in the echo command.
        # echo "version={}" formats the result as 'version=x.x.x' by inserting
        # the extracted version in place of {}.

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Test
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with: # with keyword is used to pass inputs to actions
        go-version: '1.20'

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Upload Artifact
      # Uploads a file or directory as a build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ci # name of the artifact
        path: ./ci # path of the artifact

  deploy:
    needs: [build, test, version-check] # this job will run after the build job is completed
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifact
        uses: actions/download-artifact@v3
        with:
          name: ci # name of the artifact
      - name: Output files in current folder
        run: ls
      - name: Output the version
        run: echo "Version ${{ needs.version-check.outputs.version }}"
      - name: Deploy
        run: echo "Deploying... (mimicking a deployment)"
